# Netlify configuration for Inlev
[build]
  publish = "public"
  command = ""

[build.environment]
  NODE_VERSION = "20"

# Pretty URL redirects to folder indexes
[[redirects]]
  from = "/plock"
  to = "/plock/"
  status = 301
  force = true

[[redirects]]
  from = "/trav"
  to = "/trav/"
  status = 301
  force = true

[[redirects]]
  from = "/statistik"
  to = "/statistik/"
  status = 301
  force = true

# Optional: keep downloads/ direct file serving without transformation
[[headers]]
  for = "/downloads/*"
  [headers.values]
    Cache-Control = "public, max-age=3600"
