
[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/store/*"
  to = "/.netlify/functions/store"
  status = 200

[[redirects]]
  from = "/api/auth/*"
  to = "/.netlify/functions/auth"
  status = 200

[[redirects]]
  from = "/api/admin/*"
  to = "/.netlify/functions/auth"
  status = 200
