services:
  - type: web
    name: bigplus-api
    env: node
    rootDir: bigplus-api
    plan: free
    buildCommand: npm install --omit=dev
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false

  - type: web
    name: trav-api
    env: node
    rootDir: trav-api
    plan: free
    buildCommand: npm install --omit=dev
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: TRAV_MONGODB_DB
        value: travet
