[build]
  # Change 'public' if your built static files live elsewhere
  publish = "public"
  functions = "netlify/functions"

# Keep your existing redirects; add this one to forward /api/auth/* to the 'auth' function
[[redirects]]
  from = "/api/auth/*"
  to = "/.netlify/functions/auth/:splat"
  status = 200
  force = true
