const crypto = require("crypto");
const express = require("express");
const { ObjectId } = require("mongodb");
const { species: defaultSpecies } = require("../data/catalog");
const { achievements: defaultAchievements } = require("../data/admin-catalog");
const { requireAdmin } = require("./auth");

const router = express.Router();
const METRICS = new Set(["bigplusCount", "speciesCount", "pikeOver100", "catchCount", "friendCount", "lengthOver100", "streak"]);
const DUEL_CATEGORIES = ["fish_species", "lures", "gear", "brands", "methods", "places", "boat", "weather", "fun"];
function idFrom(value) { const normalized = String(value || "").trim().toLowerCase().replace(/[^a-z0-9_-]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 60); return normalized || crypto.randomUUID(); }
function finiteNumber(value, fallback) { const number = Number(String(value ?? "").replace(",", ".")); return Number.isFinite(number) ? number : fallback; }
function cleanSpecies(body, current = {}) { const name = String(body.name ?? current.name ?? "").trim().slice(0, 80); const minCm = finiteNumber(body.minCm ?? current.minCm, 0); const factor = finiteNumber(body.factor ?? current.factor, 0.00001); if (!name || minCm < 0 || minCm > 1000 || factor <= 0 || factor > 1) return { error: "Ange artnamn, minsta längd 0–1000 cm och en giltig viktfaktor." }; return { value: { id: idFrom(body.id ?? current.id ?? name), name, minCm, factor, sortOrder: finiteNumber(body.sortOrder ?? current.sortOrder, 0) } }; }
function cleanAchievement(body, current = {}) { const title = String(body.title ?? current.title ?? "").trim().slice(0, 80); const description = String(body.description ?? current.description ?? "").trim().slice(0, 180); const metric = String(body.metric ?? current.metric ?? "catchCount"); const target = Math.round(finiteNumber(body.target ?? current.target, 1)); const points = Math.round(finiteNumber(body.points ?? current.points, 0)); const image = String(body.image ?? body.imageUrl ?? current.image ?? "").trim().slice(0, 240); if (!title || !description || !METRICS.has(metric) || target < 1 || target > 100000 || points < 0 || points > 100000 || (image && !/^\/bigplus\/assets\/achievements\/[a-z0-9-]+\.png$/.test(image))) return { error: "Fyll i rubrik, beskrivning, giltigt mål, poäng och välj en giltig bild." }; return { value: { id: idFrom(body.id ?? current.id ?? title), title, description, metric, target, points, image, visible: body.visible ?? current.visible !== false, sortOrder: finiteNumber(body.sortOrder ?? current.sortOrder, 0) } }; }
function cleanDuel(body, current = {}) { const question = String(body.question ?? current.question ?? "").trim().slice(0, 120); const optionAText = String(body.optionAText ?? current.optionA?.text ?? "").trim().slice(0, 50); const optionBText = String(body.optionBText ?? current.optionB?.text ?? "").trim().slice(0, 50); const category = DUEL_CATEGORIES.includes(body.category ?? current.category) ? (body.category ?? current.category) : "fun"; const status = ["active", "closed"].includes(body.status ?? current.status) ? (body.status ?? current.status) : "active"; const featuredType = ["none", "daily"].includes(body.featuredType ?? current.featuredType) ? (body.featuredType ?? current.featuredType) : "none"; if (!question || !optionAText || !optionBText || optionAText.toLowerCase() === optionBText.toLowerCase()) return { error: "Fyll i en fråga och två olika alternativ." }; return { value: { question, optionA: { text: optionAText, votes: Number(current.optionA?.votes) || 0 }, optionB: { text: optionBText, votes: Number(current.optionB?.votes) || 0 }, category, status, featuredType, updatedAt: new Date() } }; }
async function ensureSeed(db) { const species = db.collection("species"); if (!await species.findOne({})) await species.insertMany(defaultSpecies.map((item, index) => ({ ...item, sortOrder: index }))); const achievements = db.collection("achievements"); if (!await achievements.findOne({})) await achievements.insertMany(defaultAchievements.map((item, index) => ({ ...item, sortOrder: index }))); }
function publicSpecies(item) { return { id: String(item.id), name: item.name, minCm: Number(item.minCm) || 0, factor: Number(item.factor) || 0.00001, sortOrder: Number(item.sortOrder) || 0 }; }
function publicAchievement(item) { return { id: String(item.id), title: item.title, description: item.description, metric: item.metric, target: Number(item.target) || 1, points: Number(item.points) || 0, image: item.image || "", visible: item.visible !== false, sortOrder: Number(item.sortOrder) || 0 }; }
function publicAdminDuel(item) { const optionA = { text: item.optionA?.text || "", votes: Number(item.optionA?.votes) || 0 }; const optionB = { text: item.optionB?.text || "", votes: Number(item.optionB?.votes) || 0 }; return { id: String(item._id), question: item.question || "", optionA, optionB, category: item.category || "fun", status: item.status || "active", featuredType: item.featuredType || "none", totalVotes: optionA.votes + optionB.votes, createdAt: item.createdAt || null, updatedAt: item.updatedAt || null }; }
function publicAdminUser(user) { return { id: String(user._id), name: user.name || "Namnlös", email: user.email || "", role: user.role === "admin" ? "admin" : "user", photo: user.photo || "", createdAt: user.createdAt || null, lastSeenAt: user.lastSeenAt || null }; }
function objectId(value) { return ObjectId.isValid(value) ? new ObjectId(value) : null; }
router.use(requireAdmin);
router.get("/admin/overview", async (req, res, next) => { try { await ensureSeed(req.db); const now = new Date(); const onlineSince = new Date(Date.now() - 15 * 60 * 1000); const [users, catches, onlineSessions, species, achievements, recentUsers] = await Promise.all([req.db.collection("users").countDocuments(), req.db.collection("catches").countDocuments(), req.db.collection("sessions").find({ expiresAt: { $gt: now }, lastSeenAt: { $gt: onlineSince } }, { projection: { userId: 1 } }).toArray(), req.db.collection("species").find({}).sort({ sortOrder: 1, name: 1 }).toArray(), req.db.collection("achievements").find({}).sort({ sortOrder: 1, title: 1 }).toArray(), req.db.collection("users").find({}, { projection: { passwordHash: 0 } }).sort({ createdAt: -1 }).limit(5).toArray()]); res.json({ stats: { users, online: new Set(onlineSessions.map((item) => String(item.userId))).size, catches, species: species.length, achievements: achievements.length, visibleAchievements: achievements.filter((item) => item.visible !== false).length }, recentUsers: recentUsers.map((user) => ({ id: String(user._id), name: user.name, email: user.email, role: user.role, createdAt: user.createdAt })), lastUpdated: now.toISOString() }); } catch (error) { next(error); } });
router.get("/admin/species", async (req, res, next) => { try { await ensureSeed(req.db); res.json((await req.db.collection("species").find({}).sort({ sortOrder: 1, name: 1 }).toArray()).map(publicSpecies)); } catch (error) { next(error); } });
router.post("/admin/species", async (req, res, next) => { try { const cleaned = cleanSpecies(req.body || {}); if (cleaned.error) return res.status(400).json({ error: cleaned.error }); if (await req.db.collection("species").findOne({ id: cleaned.value.id })) return res.status(409).json({ error: "Det finns redan en art med det ID:t." }); await req.db.collection("species").insertOne(cleaned.value); res.status(201).json(publicSpecies(cleaned.value)); } catch (error) { next(error); } });
router.patch("/admin/species/:id", async (req, res, next) => { try { const collection = req.db.collection("species"); const current = await collection.findOne({ id: req.params.id }); if (!current) return res.status(404).json({ error: "Arten hittades inte." }); const cleaned = cleanSpecies(req.body || {}, current); if (cleaned.error) return res.status(400).json({ error: cleaned.error }); await collection.updateOne({ _id: current._id }, { $set: cleaned.value }); res.json(publicSpecies({ ...current, ...cleaned.value })); } catch (error) { next(error); } });
router.delete("/admin/species/:id", async (req, res, next) => { try { const result = await req.db.collection("species").deleteOne({ id: req.params.id }); if (!result.deletedCount) return res.status(404).json({ error: "Arten hittades inte." }); res.status(204).end(); } catch (error) { next(error); } });
router.get("/admin/achievements", async (req, res, next) => { try { await ensureSeed(req.db); res.json((await req.db.collection("achievements").find({}).sort({ sortOrder: 1, title: 1 }).toArray()).map(publicAchievement)); } catch (error) { next(error); } });
router.get("/admin/duels", async (req, res, next) => { try { const items = await req.db.collection("duels").find({}).sort({ createdAt: -1 }).toArray(); res.json(items.map(publicAdminDuel)); } catch (error) { next(error); } });
router.post("/admin/duels", async (req, res, next) => { try { const cleaned = cleanDuel(req.body || {}); if (cleaned.error) return res.status(400).json({ error: cleaned.error }); const now = new Date(); const duel = { ...cleaned.value, creatorUserId: req.user._id, createdAt: now, updatedAt: now }; const result = await req.db.collection("duels").insertOne(duel); res.status(201).json(publicAdminDuel({ ...duel, _id: result.insertedId })); } catch (error) { next(error); } });
router.patch("/admin/duels/:id", async (req, res, next) => { try { const id = objectId(req.params.id); if (!id) return res.status(400).json({ error: "Ogiltig duell." }); const collection = req.db.collection("duels"); const current = await collection.findOne({ _id: id }); if (!current) return res.status(404).json({ error: "Duellen hittades inte." }); const cleaned = cleanDuel(req.body || {}, current); if (cleaned.error) return res.status(400).json({ error: cleaned.error }); await collection.updateOne({ _id: id }, { $set: cleaned.value }); res.json(publicAdminDuel({ ...current, ...cleaned.value })); } catch (error) { next(error); } });
router.delete("/admin/duels/:id", async (req, res, next) => { try { const id = objectId(req.params.id); if (!id) return res.status(400).json({ error: "Ogiltig duell." }); const result = await req.db.collection("duels").deleteOne({ _id: id }); if (!result.deletedCount) return res.status(404).json({ error: "Duellen hittades inte." }); await req.db.collection("duelVotes").deleteMany({ duelId: id }); res.status(204).end(); } catch (error) { next(error); } });
router.get("/admin/users", async (req, res, next) => { try { const users = await req.db.collection("users").find({}, { projection: { passwordHash: 0 } }).sort({ createdAt: -1 }).limit(250).toArray(); res.json(users.map(publicAdminUser)); } catch (error) { next(error); } });
router.patch("/admin/users/:id/role", async (req, res, next) => { try { const id = objectId(req.params.id); const role = req.body?.role === "admin" ? "admin" : req.body?.role === "user" ? "user" : ""; if (!id || !role) return res.status(400).json({ error: "Välj en giltig adminroll." }); const users = req.db.collection("users"); const user = await users.findOne({ _id: id }, { projection: { passwordHash: 0 } }); if (!user) return res.status(404).json({ error: "Användaren hittades inte." }); if (user.role === "admin" && role === "user" && await users.countDocuments({ role: "admin" }) <= 1) return res.status(400).json({ error: "Den sista administratören kan inte tas bort." }); await users.updateOne({ _id: id }, { $set: { role } }); res.json(publicAdminUser({ ...user, role })); } catch (error) { next(error); } });
router.post("/admin/achievements", async (req, res, next) => { try { const cleaned = cleanAchievement(req.body || {}); if (cleaned.error) return res.status(400).json({ error: cleaned.error }); if (await req.db.collection("achievements").findOne({ id: cleaned.value.id })) return res.status(409).json({ error: "Det finns redan ett achievement med det ID:t." }); await req.db.collection("achievements").insertOne(cleaned.value); res.status(201).json(publicAchievement(cleaned.value)); } catch (error) { next(error); } });
router.patch("/admin/achievements/:id", async (req, res, next) => { try { const collection = req.db.collection("achievements"); const current = await collection.findOne({ id: req.params.id }); if (!current) return res.status(404).json({ error: "Achievement hittades inte." }); const cleaned = cleanAchievement(req.body || {}, current); if (cleaned.error) return res.status(400).json({ error: cleaned.error }); await collection.updateOne({ _id: current._id }, { $set: cleaned.value }); res.json(publicAchievement({ ...current, ...cleaned.value })); } catch (error) { next(error); } });
router.delete("/admin/achievements/:id", async (req, res, next) => { try { const result = await req.db.collection("achievements").deleteOne({ id: req.params.id }); if (!result.deletedCount) return res.status(404).json({ error: "Achievement hittades inte." }); res.status(204).end(); } catch (error) { next(error); } });
router.get("/admin/backup", async (req, res, next) => { try { await ensureSeed(req.db); const [species, achievements, users, catches, duels] = await Promise.all([req.db.collection("species").find({}).toArray(), req.db.collection("achievements").find({}).toArray(), req.db.collection("users").find({}, { projection: { passwordHash: 0 } }).toArray(), req.db.collection("catches").find({}).toArray(), req.db.collection("duels").find({}).toArray()]); const clean = (item) => { const { _id, ...rest } = item; return { ...rest, id: String(_id || item.id) }; }; res.setHeader("Content-Disposition", `attachment; filename=bigplus-backup-${new Date().toISOString().slice(0, 10)}.json`); res.json({ format: "bigplus-admin-backup", version: 1, createdAt: new Date().toISOString(), species: species.map(publicSpecies), achievements: achievements.map(publicAchievement), duels: duels.map(publicAdminDuel), users: users.map(clean), catches: catches.map(clean) }); } catch (error) { next(error); } });
module.exports = router;
