const express = require("express");
const { ObjectId } = require("mongodb");
const { requireAuth } = require("./auth");

const router = express.Router();
const categories = ["fish_species", "lures", "gear", "brands", "methods", "places", "boat", "weather", "fun"];
function toId(value) { try { return new ObjectId(String(value)); } catch { return null; } }
function publicDuel(item, vote) { const a = Number(item.optionA?.votes || 0); const b = Number(item.optionB?.votes || 0); const total = a + b; return { id: String(item._id), question: item.question, optionA: { text: item.optionA.text, votes: a }, optionB: { text: item.optionB.text, votes: b }, category: item.category, featuredType: item.featuredType || "none", totalVotes: total, hasUserVoted: Boolean(vote), userChoice: vote?.choice || null, showResults: Boolean(vote), createdAt: item.createdAt, updatedAt: item.updatedAt }; }
router.get("/duels/feed", requireAuth, async (req, res, next) => { try { const items = await req.db.collection("duels").find({ status: { $ne: "closed" } }).sort({ featuredType: -1, createdAt: -1 }).limit(30).toArray(); const ids = items.map((item) => item._id); const votes = await req.db.collection("duelVotes").find({ userId: req.user._id, duelId: { $in: ids } }).toArray(); const byId = new Map(votes.map((vote) => [String(vote.duelId), vote])); res.json(items.map((item) => publicDuel(item, byId.get(String(item._id))))); } catch (error) { next(error); } });
router.get("/duels/trending", requireAuth, async (req, res, next) => { try { const items = await req.db.collection("duels").find({ status: { $ne: "closed" } }).sort({ "optionA.votes": -1, "optionB.votes": -1 }).limit(10).toArray(); res.json(items.map((item) => publicDuel(item, null))); } catch (error) { next(error); } });
router.get("/duels/daily", requireAuth, async (req, res, next) => { try { const item = await req.db.collection("duels").findOne({ featuredType: "daily", status: { $ne: "closed" } }, { sort: { createdAt: -1 } }); if (!item) return res.status(404).json({ error: "Ingen dagens duell." }); const vote = await req.db.collection("duelVotes").findOne({ duelId: item._id, userId: req.user._id }); res.json(publicDuel(item, vote)); } catch (error) { next(error); } });
router.get("/duels/mine", requireAuth, async (req, res, next) => { try { const items = await req.db.collection("duels").find({ creatorUserId: req.user._id }).sort({ createdAt: -1 }).toArray(); res.json(items.map((item) => publicDuel(item, null))); } catch (error) { next(error); } });
router.get("/duels/my-votes", requireAuth, async (req, res, next) => { try { const votes = await req.db.collection("duelVotes").find({ userId: req.user._id }).sort({ createdAt: -1 }).toArray(); res.json(votes.map((vote) => ({ id: String(vote._id), duelId: String(vote.duelId), userId: String(vote.userId), choice: vote.choice, createdAt: vote.createdAt }))); } catch (error) { next(error); } });
router.get("/duels/:duelId", requireAuth, async (req, res, next) => { try { const duelId = toId(req.params.duelId); if (!duelId) return res.status(400).json({ error: "Ogiltig duell." }); const item = await req.db.collection("duels").findOne({ _id: duelId }); if (!item) return res.status(404).json({ error: "Duellen finns inte." }); const vote = await req.db.collection("duelVotes").findOne({ duelId, userId: req.user._id }); res.json(publicDuel(item, vote)); } catch (error) { next(error); } });
router.get("/duels/:duelId/results", requireAuth, async (req, res, next) => { try { const duelId = toId(req.params.duelId); if (!duelId) return res.status(400).json({ error: "Ogiltig duell." }); const item = await req.db.collection("duels").findOne({ _id: duelId }); if (!item) return res.status(404).json({ error: "Duellen finns inte." }); const vote = await req.db.collection("duelVotes").findOne({ duelId, userId: req.user._id }); const result = publicDuel(item, vote); if (!vote && item.status !== "closed") return res.status(403).json({ error: "Rösta först för att se resultatet." }); res.json({ duelId: result.id, optionA: { ...result.optionA, percent: result.totalVotes ? Math.round(result.optionA.votes / result.totalVotes * 100) : 0 }, optionB: { ...result.optionB, percent: result.totalVotes ? Math.round(result.optionB.votes / result.totalVotes * 100) : 0 }, totalVotes: result.totalVotes, userChoice: result.userChoice }); } catch (error) { next(error); } });
router.post("/duels", requireAuth, async (req, res, next) => { try { const question = String(req.body?.question || "").trim().slice(0, 120); const a = String(req.body?.optionAText || "").trim().slice(0, 50); const b = String(req.body?.optionBText || "").trim().slice(0, 50); const category = categories.includes(req.body?.category) ? req.body.category : "fun"; if (!question || !a || !b || a.toLowerCase() === b.toLowerCase()) return res.status(400).json({ error: "Fyll i en fråga och två olika alternativ." }); const duel = { question, optionA: { text: a, votes: 0 }, optionB: { text: b, votes: 0 }, category, creatorUserId: req.user._id, status: "active", featuredType: "none", createdAt: new Date(), updatedAt: new Date() }; const result = await req.db.collection("duels").insertOne(duel); res.status(201).json(publicDuel({ ...duel, _id: result.insertedId }, null)); } catch (error) { next(error); } });
router.post("/duels/:duelId/vote", requireAuth, async (req, res, next) => { try { const duelId = toId(req.params.duelId); const choice = req.body?.choice === "B" ? "B" : req.body?.choice === "A" ? "A" : null; if (!duelId || !choice) return res.status(400).json({ error: "Ogiltig röst." }); const duel = await req.db.collection("duels").findOne({ _id: duelId, status: { $ne: "closed" } }); if (!duel) return res.status(404).json({ error: "Duellen finns inte." }); const existing = await req.db.collection("duelVotes").findOne({ duelId, userId: req.user._id }); if (existing) return res.status(409).json({ error: "Du har redan röstat." }); await req.db.collection("duelVotes").insertOne({ duelId, userId: req.user._id, choice, createdAt: new Date() }); const field = choice === "A" ? "optionA.votes" : "optionB.votes"; await req.db.collection("duels").updateOne({ _id: duelId }, { $inc: { [field]: 1 }, $set: { updatedAt: new Date() } }); const updated = await req.db.collection("duels").findOne({ _id: duelId }); res.json(publicDuel(updated, { choice })); } catch (error) { if (error?.code === 11000) return res.status(409).json({ error: "Du har redan röstat." }); next(error); } });
module.exports = router;
